### ISSUE TITLE
Build flags?

### ISSUE THREAD

**Issue by ansel1** [houqp/sqlvet#14]
sqlvet is bombing because the code is referencing a function which is only visible when compiled with a particular build flag.  But I don't see a documented way to tell sqlvet to use build flags when it runs.

**Comment by houqp** [comment]
@ansel1 have you tried the fix in https://github.com/houqp/sqlvet/pull/10?

**Comment by houqp** [comment]
triggered a new release 1.1.4 to include the build flag feature

**Comment by ansel1** [comment]
Yeah, turns out it was a colleague here that submitted that.  I'm trying it out, but still getting the same error.  I'll keep investigating.

**Comment by ansel1** [comment]
Ok, looks like the patch works.  Was still getting the error because the format of the build flags was incorrect.
