### ISSUE TITLE
invalid table name error when VIEW is used

### ISSUE THREAD

**Issue by valichek** [houqp/sqlvet#27]
Getting error 
```
ERROR: invalid table name: tbl_extended
```

on any SELECT

```
 SELECT * FROM tbl_extended;
```

when `VIEW` is created:

```
CREATE VIEW tbl_extended AS
SELECT tbl.*,
       tbl1.title   as prop1,
       tbl2.type as prop2
FROM "operations"
         LEFT JOIN tbl1 ON tbl1.id = tbl.tbl1_id
         LEFT JOIN tbl2 ON tbl2.id = tbl.tbl2_id;
```

**Comment by houqp** [comment]
Good catch, @valichek i think the schema parsing switch block needs to be extended to take views into account, see: https://github.com/houqp/sqlvet/blob/4e66a9896fb9d1dc54c810a5e54d8119e507d44c/pkg/schema/postgres.go#L26

**Comment by valichek** [comment]
@houqp do you need any help to fix this?

**Comment by houqp** [comment]
Yes, would appreciate if you can send a MR. I am happy to help review and add pointers to help unblock the fix.

**Comment by samiam2013** [comment]
@valichek I already have a short backlog of things I want to do for this repo, but just my 2 cents: the tests are already fairly exhaustive, if I had to guess Mr. Hou worked on it in a style approaching TDD. You should be able to add test cases for both this and your other issue and step through with a debugger to see where things break/need changes. At least that made was was an unimaginable change manageable for me.

I'm also happy to help if I can, though I have little confidence it would be as useful as his help.
